#!/bin/sh

main() {
    if [ -f /src/cronjob ]; then
        echo " ---> Importing cronjob"
        crontab -l > /tmp/tmpcron.txt
        cat /src/cronjob >> /tmp/tmpcron.txt
        crontab /tmp/tmpcron.txt
        rm /tmp/tmpcron.txt
    fi
}

main "$@"
