#!/bin/sh

main() {
    if [ -f /src/pre-run ]; then
        if [ ! -x /src/pre-run ]; then
            echo "WARNING: Script pre-run not executable."
        fi
    fi

    if [ -x /src/pre-run ]; then
        echo " ---> Running pre-run"
        /bin/sh /src/pre-run
    fi
}

main "$@"
