#!/bin/sh

main() {
    # Run pre-run user scripts if any
    pre-run
    # Start cron daemon if cronjob present
    if [ -f /src/cronjob ]; then
        echo " ---> Starting cron daemon"
        crond
    fi
    # Run migrate command (need database defined)
    python manage.py migrate
    # Run Collect static (need a mounted volume on `/static`)
    python manage.py collectstatic --no-input --clear
    # Run Gunicorn
    APP=`python manage.py shell -c 'import os; print(os.environ.get("DJANGO_SETTINGS_MODULE").split(".")[0])'`
    echo " ---> Starting application: ${APP}"
    gunicorn "${APP}.wsgi:application" -w ${GUNICORN_WORKER} --bind=${GUNICORN_BIND_IP}:${GUNICORN_BIND_PORT}
}

main "$@"
